image: node:6.9.4

pipelines:

  default:
    - step:
        caches:
          - node
        script:
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn
          - npm run cover

  tags:
    '*':
      - step:
          caches:
            - node
          script:
            - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1
            - export PATH=$HOME/.yarn/bin:$PATH
            - yarn
            - npm run cover
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker build --force-rm=true -t=$REPO_NAME .
            - docker tag $REPO_NAME $DOCKER_TEAMNAME/$REPO_NAME:$BITBUCKET_TAG
            - docker push $DOCKER_TEAMNAME/$REPO_NAME:$BITBUCKET_TAG

  branches:
    develop:
      - step:
          caches:
            - node
          script:
            - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1
            - export PATH=$HOME/.yarn/bin:$PATH
            - yarn
            - npm run cover
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker build --force-rm=true -t=$REPO_NAME .
            - docker tag $REPO_NAME $DOCKER_TEAMNAME/$REPO_NAME:latest
            - docker push $DOCKER_TEAMNAME/$REPO_NAME:latest

options:
  docker: true